### ISSUE TITLE
problems with fillPatternImage in 4.0.7, works in 4.0.5

### ISSUE THREAD

**Issue by rypskar** [konvajs/konva#729]
Layer.draw() fails when the layer have a Konva.Rect with a fillPatternImage. Removing the fillPatternImage and the layer draws. It works in 4.0.5, but is broken in 4.0.6 and 4.0.7

Stacktrace:
TypeError: Argument 1 of CanvasPattern.setTransform does not implement interface SVGMatrix
__getFillPattern Shape.js:113
    _getCache Node.js:115
    _getFillPattern Shape.js:107
    _fillPattern Context.js:383
    _fill Context.js:425
    fillStrokeShape Context.js:96
    _sceneFunc Rect.js:56
    drawScene Shape.js:354
    _drawChildren Container.js:249
    each Util.js:36
    _drawChildren Container.js:248
    drawScene Container.js:200
    _drawChildren Container.js:249
    each Util.js:36
    _drawChildren Container.js:248
    drawScene Container.js:200
    drawScene Layer.js:115
    draw Node.js:1132

**Comment by lavrton** [comment]
Should work ok with `konva@4.0.8`
