### ISSUE TITLE
Typescript compatibility issue

### ISSUE THREAD

**Issue by Humzabj** [konvajs/konva#802]
I went through the issue logs but I don't see anyone using typescript@'>=2.4.2 <2.7.0'

Obviously, the minimum requirement for the package is typescript@^3.7.2
The library works just fine if I skip the TS errors. But, my project won't be able to compile automatically if I don't fix this issue. 
I'm new to the community and I don't know what to do about this. I can manually fix the lib to make it work properly with older TS version. The problem arrises due to in-line 'import' statements.
One such example can be found in konva/types/BaseLayer.d.ts (20, 25):
`getContext(): import("./Context").Context;`

The lib works fine if I make this a separate import statement as following:

`import { Context } from './Context';
getContext(): Context;`

**Angular Version details:**

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              5.5.11
typescript                        2.5.3
webpack                           4.8.3

**Error log on compialtion:**
`
ERROR in node_modules/konva/types/BaseLayer.d.ts(20,19): error TS1110: Type expected.
node_modules/konva/types/BaseLayer.d.ts(20,26): error TS1003: Identifier expected.
node_modules/konva/types/BaseLayer.d.ts(20,38): error TS1144: '{' or ';' expected.
node_modules/konva/types/PointerEvents.d.ts(7,68): error TS1005: '>' expected.
node_modules/konva/types/PointerEvents.d.ts(7,99): error TS1109: Expression expected.
node_modules/konva/types/Shape.d.ts(71,18): error TS1110: Type expected.
node_modules/konva/types/Shape.d.ts(71,25): error TS1003: Identifier expected.
node_modules/konva/types/Shape.d.ts(71,36): error TS1144: '{' or ';' expected.
node_modules/konva/types/Stage.d.ts(53,29): error TS1005: '>' expected.
node_modules/konva/types/Stage.d.ts(53,36): error TS1003: Identifier expected.
node_modules/konva/types/Stage.d.ts(53,45): error TS1144: '{' or ';' expected.
node_modules/konva/types/Stage.d.ts(53,51): error TS1139: Type parameter declaration expected.
node_modules/konva/types/Stage.d.ts(53,58): error TS1003: Identifier expected.
node_modules/konva/types/Stage.d.ts(53,67): error TS1144: '{' or ';' expected.
node_modules/konva/types/Stage.d.ts(53,78): error TS1005: '=' expected.
node_modules/konva/types/Stage.d.ts(53,80): error TS1109: Expression expected.
node_modules/konva/types/index-types.d.ts(39,26): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(41,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(42,22): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(43,28): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(45,45): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(47,4): error TS1005: '(' expected.
node_modules/konva/types/index-types.d.ts(49,35): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(54,7): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(54,59): error TS1005: '(' expected.
node_modules/konva/types/index-types.d.ts(56,40): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(57,27): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(57,64): error TS1005: '(' expected.
node_modules/konva/types/index-types.d.ts(58,33): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(60,41): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(61,34): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(61,67): error TS1005: '(' expected.
node_modules/konva/types/index-types.d.ts(62,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(64,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(65,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(66,37): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(68,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(69,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(70,29): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(72,40): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(73,27): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(75,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(76,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(78,33): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(80,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(81,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(82,29): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(83,37): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(85,40): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(86,27): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(88,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(89,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(90,38): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(92,34): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(93,21): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(94,27): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(95,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(96,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(97,29): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(98,37): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(99,24): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(100,30): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(101,38): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(102,25): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(103,31): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(104,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(105,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(106,29): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(107,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(108,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(109,29): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(110,34): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(111,21): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(112,27): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(113,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(114,22): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(115,28): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(116,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(117,22): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(118,28): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(119,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(120,22): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(121,28): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(122,45): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(123,32): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(124,38): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(125,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(126,22): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(127,28): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(128,37): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(129,24): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(130,30): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(131,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(132,22): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(133,28): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(134,35): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(135,22): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(136,28): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(137,39): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(138,26): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(139,32): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(140,42): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(141,29): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(142,35): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(143,36): error TS1005: '=' expected.
node_modules/konva/types/index-types.d.ts(144,23): error TS1110: Type expected.
node_modules/konva/types/index-types.d.ts(145,29): error TS1110: Type expected.
node_modules/konva/types/shapes/Label.d.ts(9,16): error TS1110: Type expected.
node_modules/konva/types/shapes/Label.d.ts(9,23): error TS1003: Identifier expected.
node_modules/konva/types/shapes/Label.d.ts(9,33): error TS1144: '{' or ';' expected.
node_modules/konva/types/shapes/Label.d.ts(9,39): error TS1139: Type parameter declaration expected.
node_modules/konva/types/shapes/Label.d.ts(9,46): error TS1003: Identifier expected.
node_modules/konva/types/shapes/Label.d.ts(9,56): error TS1144: '{' or ';' expected.
node_modules/konva/types/shapes/Label.d.ts(9,67): error TS1005: '=' expected.
node_modules/konva/types/shapes/Label.d.ts(9,68): error TS1109: Expression expected.
node_modules/konva/types/shapes/Transformer.d.ts(38,21): error TS1005: '>' expected.
node_modules/konva/types/shapes/Transformer.d.ts(38,28): error TS1003: Identifier expected.
node_modules/konva/types/shapes/Transformer.d.ts(38,38): error TS1144: '{' or ';' expected.
node_modules/konva/types/shapes/Transformer.d.ts(38,49): error TS1005: '=' expected.
node_modules/konva/types/shapes/Transformer.d.ts(38,50): error TS1109: Expression expected.
`

**Comment by lavrton** [comment]
`konva/types/BaseLayer.d.ts` is generated automatically by TS. So I don't think we should edit the file manually.

I don't have any plans to support old versions of TS. You can just ignore those errors or remove all types from the installed konva package.

**Comment by Humzabj** [comment]
@lavrton Cheers!. I've found a workaround for this. Just in case anybody needs this:
The 
`"exclude": ["**/*.d.ts"] 
`property in my _tsconfig.json_ file wouldn't work becasue of the 
`"baseUrl": "./".
` property.
So, I had to install the 'patch-package' via npm into my project and manually remove the auto-generated 'node_modules/konva/types' folder.

**Comment by fspezi** [comment]
I solved using "patch-package" as suggested by @Humzabj, but instead of delete "node_modules/konva/types" folder, I changed files to solve issues. Then I run `ngx patch-pachage konva` to save the patch.

This is the "types" folder with changes. [konva-types.zip](https://github.com/konvajs/konva/files/4718638/konva-types.zip)

Ant this is the patch in "project/patches" folder: [konva+6.0.0.zip](https://github.com/konvajs/konva/files/4718641/konva%2B6.0.0.zip)

It works in my project with TypeScript 2.7.2 (Angular 5.2)
